CREATE TABLE block ( id TEXT PRIMARY KEY NOT NULL, screen_name TEXT KEY NOT NULL COLLATE NOCASE, prev_id TEXT, next_id TEXT);
CREATE TABLE entities ( tweetid TEXT KEY NOT NULL, type TEXT NOT NULL, indices TEXT NOT NULL, id TEXT, url TEXT, media_url TEXT, display_url TEXT, expanded_url TEXT, media_type TEXT, screen_name TEXT, name TEXT, text TEXT);
CREATE TABLE help_configuration ( last_update_time TIMESTAMP, characters_reserved_per_media INTEGER NOT NULL, max_media_per_upload INTEGER NOT NULL, photo_size_limit INTEGER NOT NULL, short_url_length_https INTEGER NOT NULL, short_url_length INTEGER NOT NULL);
CREATE TABLE place ( id TEXT PRIMARY KEY NOT NULL, name TEXT, country_code TEXT, country TEXT, attributes TEXT, url TEXT, bb_c0x FLOAT, bb_c0y FLOAT, bb_c1x FLOAT, bb_c1y FLOAT, bb_c2x FLOAT, bb_c2y FLOAT, bb_c3x FLOAT, bb_c3y FLOAT, bb_type TEXT, full_name TEXT, contained_within_id TEXT, place_type TEXT);
CREATE TABLE refresh_time ( view INTEGER, screen_name TEXT, refresh_time TIMESTAMP);
CREATE TABLE search_history ( query_string VARCHAR(20), query_time TIMESTAMP);
CREATE TABLE timeline ( timeline TEXT NOT NULL, tweet_id TEXT KEY NOT NULL, FOREIGN KEY(tweet_id) REFERENCES tweet(id) ON DELETE CASCADE);
CREATE TABLE trend ( trendname VARCHAR(20), searchurl VARCHAR(40), asof TEXT);
CREATE TABLE tweet ( id TEXT PRIMARY KEY NOT NULL, type TEXT, text TEXT, source TEXT, truncated BOOLEAN, created_at TEXT, coordinates TEXT, geo TEXT, place_id TEXT, in_reply_to_status_id TEXT, in_reply_to_user_id TEXT, favorited BOOLEAN, in_reply_to_screen_name TEXT, retweet_count TEXT, retweeted BOOLEAN, retweet_id TEXT, sender_screen_name TEXT, contributors TEXT, recipient_id TEXT, recipient_screen_name TEXT, current_user_retweet_id TEXT, modified_date INTEGER);
CREATE TABLE version ( version INT PRIMARY KEY NOT NULL);
